baseURL = "https://devzone.solutions/"
languageCode = "en-us"
title = "DevZone Solutions"
theme = 'divezone'
enableGitInfo = true
enableRobotsTXT = true
disableKinds = ["rss","taxonomy","term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  writeStats = true

[module]
  [[module.mounts]]
    source = 'node_modules/@divezone/divezone-web-styles/static'
    target = 'static'
  [[module.mounts]]
    source = 'static'
    target = 'static'